### ISSUE TITLE
Pesquisa João

### ISSUE THREAD

**Issue by GuiGa455** [GuiGa455/Tcc-Diagnostico#8]
TCC de auxilio ao diagnostico de covid usando machine learning e auxilio ao diagnostico de covid usando deep learning(aplicação da IA na área médica)

**Comment by unifjassis** [comment]
https://repositorio.animaeducacao.com.br/bitstream/ANIMA/13792/1/TCC.pdf

https://repositorio.unifesp.br/bitstream/handle/11600/60713/Monografia%20TCC2%20Vers%c3%a3o%20Reposit%c3%b3rio.pdf?sequence=5&isAllowed=y
